"""Type stubs for sexpdata — no upstream stubs available."""

from typing import IO

class Symbol(str):
    def value(self) -> str: ...

class String(str): ...
class Quoted: ...

type SExpItem = Symbol | str | int | float | list[SExpItem]
type SExp = list[SExpItem]

class Brackets(list[SExpItem]): ...
class Parens(list[SExpItem]): ...

def load(fileobj: IO[str]) -> SExp: ...
def loads(string: str) -> SExp: ...
def dump(obj: object, fileobj: IO[str]) -> None: ...
def dumps(obj: object) -> str: ...
def parse(string: str) -> list[SExp]: ...
def car(obj: SExp) -> SExpItem: ...
def cdr(obj: SExp) -> SExp: ...
