from __future__ import annotations

from pathlib import Path

FIXTURES = Path(__file__).resolve().parent / "fixtures"
UPSTREAM_FIXTURES = FIXTURES.parent / "upstream"

OPENCELLULAR_BREAKOUT_ROOT = UPSTREAM_FIXTURES / "opencellular/electronics/breakout"
OPENCELLULAR_BREAKOUT_IPC356 = (
    OPENCELLULAR_BREAKOUT_ROOT / "gerbers/OC_CONNECT-1_BREAKOUT_LIFE-3.ipc"
)
OPENCELLULAR_BREAKOUT_NETLIST = OPENCELLULAR_BREAKOUT_ROOT / "schematic/Netlist"

OPENCELLULAR_SYNC_ROOT = UPSTREAM_FIXTURES / "opencellular/electronics/sync"
OPENCELLULAR_SYNC_IPC356 = OPENCELLULAR_SYNC_ROOT / "gerbers/Fb_Connect1_SYNC_Life-3.ipc"
OPENCELLULAR_SYNC_NETLIST = OPENCELLULAR_SYNC_ROOT / "schematics/Netlist"

CP_SMARTGARDEN_ALLEGRO = (
    UPSTREAM_FIXTURES / "cp-smartgarden/Document/Hardware/mcu/swrc319/Cadence/Allegro"
)
CP_SMARTGARDEN_NETLIST = CP_SMARTGARDEN_ALLEGRO
CP_SMARTGARDEN_PLACEMENT_LOG = CP_SMARTGARDEN_ALLEGRO / "log/plctxt.log"

ROHM_GERBER_ROOT = (
    UPSTREAM_FIXTURES / "rohm-stepper-driver/Design Files for Rev 1.0/Gerbers & Panel CAD"
)
ROHM_DRILL = ROHM_GERBER_ROOT / "DRILL.DRL"
ROHM_VIEW_ENV = ROHM_GERBER_ROOT / "VIEW.ENV"
ROHM_REPORT = ROHM_GERBER_ROOT / "REPORT.DOC"
