"""Type stubs for olefile — no upstream stubs available."""

from typing import IO

def isOleFile(filename: str | bytes | IO[bytes] | None = None) -> bool: ...

class OleFileIO:
    def __init__(
        self,
        filename: str | bytes | IO[bytes] | None = None,
    ) -> None: ...
    def openstream(self, stream: str | list[str]) -> IO[bytes]: ...
    def exists(self, stream: str | list[str]) -> bool: ...
    def listdir(
        self,
        streams: bool = ...,
        storages: bool = ...,
    ) -> list[list[str]]: ...
    def get_size(self, filename: str | list[str]) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> OleFileIO: ...
    def __exit__(self, *args: object) -> None: ...
