"""Reusable Allegro sidecar and manufacturing-output oracle helpers.

These helpers parse independent evidence generated by Cadence or downstream
manufacturing tools. They validate parser output in later Allegro slices; they
do not parse native ``.brd`` data and must not become a loader fallback.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from dataclasses import dataclass
from enum import StrEnum
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

KICAD_CONVERSION_TIMEOUT_SECONDS = 120


class OracleEvidenceKind(StrEnum):
    IPC356 = "ipc356"
    EXCELLON_DRILL = "excellon_drill"
    GERBER_MANIFEST = "gerber_manifest"
    PACKAGED_NETLIST = "packaged_netlist"
    PLACEMENT = "placement"
    KICAD_CONVERSION = "kicad_conversion"


ALLEGRO_ORACLE_CAPABILITIES = frozenset(
    {
        "component_identity",
        "connectivity",
        "constraints",
        "drills",
        "geometry",
        "placement",
        "placement_count",
        "stackup",
    }
)


@dataclass(frozen=True, slots=True)
class OracleCoverage:
    validates: frozenset[str]
    cannot_prove: frozenset[str]


ALLEGRO_ORACLE_COVERAGE: dict[OracleEvidenceKind, OracleCoverage] = {
    OracleEvidenceKind.IPC356: OracleCoverage(
        validates=frozenset({"connectivity", "geometry", "stackup"}),
        cannot_prove=ALLEGRO_ORACLE_CAPABILITIES
        - frozenset({"connectivity", "geometry", "stackup"}),
    ),
    OracleEvidenceKind.EXCELLON_DRILL: OracleCoverage(
        validates=frozenset({"drills", "geometry"}),
        cannot_prove=ALLEGRO_ORACLE_CAPABILITIES - frozenset({"drills", "geometry"}),
    ),
    OracleEvidenceKind.GERBER_MANIFEST: OracleCoverage(
        validates=frozenset({"geometry", "stackup", "drills"}),
        cannot_prove=ALLEGRO_ORACLE_CAPABILITIES - frozenset({"geometry", "stackup", "drills"}),
    ),
    OracleEvidenceKind.PACKAGED_NETLIST: OracleCoverage(
        validates=frozenset({"connectivity", "component_identity"}),
        cannot_prove=ALLEGRO_ORACLE_CAPABILITIES
        - frozenset({"connectivity", "component_identity"}),
    ),
    OracleEvidenceKind.PLACEMENT: OracleCoverage(
        validates=frozenset({"placement_count"}),
        cannot_prove=ALLEGRO_ORACLE_CAPABILITIES - frozenset({"placement_count"}),
    ),
    OracleEvidenceKind.KICAD_CONVERSION: OracleCoverage(
        validates=frozenset({"connectivity", "geometry", "stackup"}),
        cannot_prove=ALLEGRO_ORACLE_CAPABILITIES
        - frozenset({"connectivity", "geometry", "stackup"}),
    ),
}


@dataclass(frozen=True, slots=True)
class Ipc356Layer:
    name: str
    material: str
    layer_type: str
    film_type: str
    number: int


@dataclass(frozen=True, slots=True)
class Ipc356TestRecord:
    record_type: str
    net_name: str
    refdes: str
    pin: str
    x_mils: float | None
    y_mils: float | None
    access_side: str

    @property
    def is_via(self) -> bool:
        return self.refdes == "VIA"


@dataclass(frozen=True, slots=True)
class Ipc356Report:
    path: Path
    version: str
    units: str
    decimal_places: int
    layers: tuple[Ipc356Layer, ...]
    test_records: tuple[Ipc356TestRecord, ...]

    @property
    def net_names(self) -> frozenset[str]:
        return frozenset(record.net_name for record in self.test_records if record.net_name)

    @property
    def component_refs(self) -> frozenset[str]:
        return frozenset(
            record.refdes for record in self.test_records if record.refdes and not record.is_via
        )


@dataclass(frozen=True, slots=True)
class DrillTool:
    code: str
    diameter_inch: float


@dataclass(frozen=True, slots=True)
class DrillHit:
    tool_code: str
    raw_x: str
    raw_y: str


@dataclass(frozen=True, slots=True)
class ExcellonDrill:
    path: Path
    units: str
    zero_suppression: str
    tools: tuple[DrillTool, ...]
    hits: tuple[DrillHit, ...]

    @property
    def hit_counts_by_tool(self) -> dict[str, int]:
        counts = {tool.code: 0 for tool in self.tools}
        for hit in self.hits:
            counts[hit.tool_code] = counts.get(hit.tool_code, 0) + 1
        return counts


@dataclass(frozen=True, slots=True)
class ViewEnvLayer:
    index: int
    layer_type: int
    aperture_table: int
    filename: str
    polarity: int
    display_order: int


@dataclass(frozen=True, slots=True)
class ViewEnvManifest:
    path: Path
    layers: tuple[ViewEnvLayer, ...]


@dataclass(frozen=True, slots=True)
class GerberReportLayer:
    index: int
    trace_count: int
    arc_count: int
    pad_count: int
    width_inch: float
    height_inch: float
    filename: str
    purpose: str


@dataclass(frozen=True, slots=True)
class GerberReport:
    path: Path
    units: str
    gerber_format: str
    drill_format: str
    layers: tuple[GerberReportLayer, ...]
    drill_aperture_counts_by_tool: dict[str, int]
    drill_aperture_pad_counts_by_tool: dict[str, int]

    @property
    def layers_by_filename(self) -> dict[str, GerberReportLayer]:
        return {layer.filename: layer for layer in self.layers}


@dataclass(frozen=True, slots=True)
class PackagedNetlistSummary:
    root: Path
    net_count: int
    node_count: int
    no_connect_node_count: int
    part_count: int
    unique_refdes_count: int
    primitive_count: int
    primitive_pin_count: int


@dataclass(frozen=True, slots=True)
class PlacementLog:
    path: Path
    board_file: str
    output_file: str
    placed_component_count: int


@dataclass(frozen=True, slots=True)
class KicadConversionReport:
    source_board: Path
    output_board: Path
    output_size_bytes: int
    layer_count: int
    stdout: str
    stderr: str


_IPC_VERSION_RE = re.compile(r"^P\s+VER\s+(.+?)\s*$")
_IPC_UNITS_RE = re.compile(r"^P\s+UNITS\s+(\S+)\s+(\S+)")
_IPC_DECIMAL_RE = re.compile(r"^C\s+Decimal Place Accuracy:\s+(\d+)\s*$")
_IPC_LAYER_RE = re.compile(r"^C\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s*$")
_IPC_COORD_RE = re.compile(r"X([+-]\d+)Y([+-]\d+)")
_IPC_ACCESS_SIDE_RE = re.compile(r"\b(S\d+)\s*$")
_PSTXNET_QUOTED_RE = re.compile(r"^\s*'([^']*)'")
_PSTXNET_NODE_RE = re.compile(r"^NODE_NAME\s+(\S+)\s+(\S+)")
_PSTXPRT_PART_RE = re.compile(r"^\s+(\S+)\s+'([^']+)':;")
_PSTCHIP_PRIMITIVE_RE = re.compile(r"^primitive '([^']+)';")
_PSTCHIP_PIN_NUMBER_RE = re.compile(r"^\s+PIN_NUMBER='")
_EXCELLON_TOOL_RE = re.compile(r"^T(\d+)C([0-9.]+)$")
_EXCELLON_TOOL_SELECT_RE = re.compile(r"^T(\d+)$")
_EXCELLON_HIT_RE = re.compile(r"^X([+-]?\d+)Y([+-]?\d+)")
_VIEW_ENV_LAYER_RE = re.compile(r"^(\d+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(\d+)\s+(\d+)$")
_REPORT_LAYER_RE = re.compile(
    r"^\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
    r"([0-9.]+)\s+([0-9.]+)\s+(\S+)\s+\(([^)]+)\)"
)
_REPORT_DRILL_APERTURE_RE = re.compile(
    r"^\s*9\d\d\s+\S+\s+[0-9.]+\s+T(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s*$"
)
_PLACEMENT_BOARD_RE = re.compile(r"^\(\s+Drawing\s+:\s+(.+?)\s+\)")
_PLACEMENT_OUTPUT_RE = re.compile(r"^\s*Create a placement by text file:\s+(.+?)\s*$")
_PLACEMENT_COUNT_RE = re.compile(r"^\s*Successfully processed\s+(\d+)\s+placed components\s*$")
_KICAD_LAYER_RE = re.compile(r"^\s*\(\d+\s+\"[^\"]+\"")


def parse_ipc356(path: Path) -> Ipc356Report:
    lines = path.read_text(errors="replace").splitlines()
    version = ""
    units = ""
    decimal_places = 0
    layers: list[Ipc356Layer] = []
    test_records: list[Ipc356TestRecord] = []
    in_layer_table = False
    seen_layer_separator = False

    for line in lines:
        if match := _IPC_VERSION_RE.match(line):
            version = match.group(1).strip()
            continue
        if match := _IPC_UNITS_RE.match(line):
            units = _ipc_units_label(match.group(1), match.group(2))
            continue
        if match := _IPC_DECIMAL_RE.match(line):
            decimal_places = int(match.group(1))
            continue
        if "BOARD LAYER INFORMATION" in line:
            in_layer_table = True
            continue
        if in_layer_table:
            if "-----" in line:
                seen_layer_separator = True
                continue
            if seen_layer_separator and line.strip() == "C":
                in_layer_table = False
                continue
            if seen_layer_separator and (match := _IPC_LAYER_RE.match(line)):
                layers.append(
                    Ipc356Layer(
                        name=match.group(1),
                        material=match.group(2),
                        layer_type=match.group(3),
                        film_type=match.group(4),
                        number=int(match.group(5)),
                    )
                )
                continue
        if line.startswith(("317", "327", "367")):
            test_records.append(_parse_ipc356_test_record(line, decimal_places, units))

    return Ipc356Report(
        path=path,
        version=version,
        units=units,
        decimal_places=decimal_places,
        layers=tuple(layers),
        test_records=tuple(test_records),
    )


def _parse_ipc356_test_record(line: str, decimal_places: int, units: str) -> Ipc356TestRecord:
    coord_match = _IPC_COORD_RE.search(line)
    x_mils = (
        _ipc_coord_to_mils(coord_match.group(1), decimal_places, units) if coord_match else None
    )
    y_mils = (
        _ipc_coord_to_mils(coord_match.group(2), decimal_places, units) if coord_match else None
    )
    refdes = line[20:26].strip()
    access_match = _IPC_ACCESS_SIDE_RE.search(line)
    return Ipc356TestRecord(
        record_type=line[:3],
        net_name=line[3:17].strip(),
        refdes=refdes,
        pin=line[27:31].strip(),
        x_mils=x_mils,
        y_mils=y_mils,
        access_side=access_match.group(1) if access_match else "",
    )


def _ipc_units_label(unit_name: str, unit_code: str) -> str:
    if unit_name == "CUST" and unit_code == "0":
        return "mils"
    if unit_name == "CUST" and unit_code == "1":
        return "mm"
    return f"{unit_name} {unit_code}"


def _ipc_coord_to_mils(value: str, decimal_places: int, units: str) -> float:
    if units != "mils":
        msg = f"IPC-D-356 coordinate unit {units!r} is not mils"
        raise ValueError(msg)
    return int(value) / (10**decimal_places)


def parse_excellon_drill(path: Path) -> ExcellonDrill:
    units = ""
    zero_suppression = ""
    current_tool = ""
    tools: list[DrillTool] = []
    hits: list[DrillHit] = []

    for raw_line in path.read_text(errors="replace").splitlines():
        line = raw_line.strip()
        if line.startswith("INCH"):
            units = "inch"
            zero_suppression = _parse_zero_suppression(line)
            continue
        if match := _EXCELLON_TOOL_RE.match(line):
            tools.append(DrillTool(code=match.group(1), diameter_inch=float(match.group(2))))
            continue
        if match := _EXCELLON_TOOL_SELECT_RE.match(line):
            current_tool = match.group(1)
            continue
        if current_tool and (match := _EXCELLON_HIT_RE.match(line)):
            hits.append(
                DrillHit(tool_code=current_tool, raw_x=match.group(1), raw_y=match.group(2))
            )

    return ExcellonDrill(
        path=path,
        units=units,
        zero_suppression=zero_suppression,
        tools=tuple(tools),
        hits=tuple(hits),
    )


def _parse_zero_suppression(line: str) -> str:
    if ",LZ" in line:
        return "trailing"
    if ",TZ" in line:
        return "leading"
    return ""


def parse_view_env_manifest(path: Path) -> ViewEnvManifest:
    layers = tuple(
        ViewEnvLayer(
            index=int(match.group(1)),
            layer_type=int(match.group(2)),
            aperture_table=int(match.group(3)),
            filename=match.group(4),
            polarity=int(match.group(5)),
            display_order=int(match.group(6)),
        )
        for line in path.read_text(errors="replace").splitlines()
        if (match := _VIEW_ENV_LAYER_RE.match(line.strip()))
    )
    return ViewEnvManifest(path=path, layers=layers)


def parse_gerber_report(path: Path) -> GerberReport:
    units = ""
    gerber_format = ""
    drill_format = ""
    layers: list[GerberReportLayer] = []
    drill_counts: dict[str, int] = {}
    drill_pad_counts: dict[str, int] = {}

    for line in path.read_text(errors="replace").splitlines():
        if line.startswith("Units = "):
            units = line.removeprefix("Units = ").strip()
            continue
        if line.startswith("Gerber format: "):
            gerber_format = line.removeprefix("Gerber format: ").strip()
            continue
        if line.startswith("Drill format: "):
            drill_format = line.removeprefix("Drill format: ").strip()
            continue
        if match := _REPORT_LAYER_RE.match(line):
            layers.append(
                GerberReportLayer(
                    index=int(match.group(1)),
                    trace_count=int(match.group(2)),
                    arc_count=int(match.group(3)),
                    pad_count=int(match.group(4)),
                    width_inch=float(match.group(5)),
                    height_inch=float(match.group(6)),
                    filename=match.group(7),
                    purpose=match.group(8),
                )
            )
            continue
        if match := _REPORT_DRILL_APERTURE_RE.match(line):
            tool_code = f"{int(match.group(1)):02d}"
            trace_count = int(match.group(2))
            arc_count = int(match.group(3))
            pad_count = int(match.group(4))
            drill_counts[tool_code] = trace_count + arc_count + pad_count
            drill_pad_counts[tool_code] = pad_count

    return GerberReport(
        path=path,
        units=units,
        gerber_format=gerber_format,
        drill_format=drill_format,
        layers=tuple(layers),
        drill_aperture_counts_by_tool=drill_counts,
        drill_aperture_pad_counts_by_tool=drill_pad_counts,
    )


def parse_packaged_netlist_summary(root: Path) -> PackagedNetlistSummary:
    pstxnet_lines = (root / "pstxnet.dat").read_text(errors="replace").splitlines()
    pstxprt_lines = (root / "pstxprt.dat").read_text(errors="replace").splitlines()
    pstchip_lines = (root / "pstchip.dat").read_text(errors="replace").splitlines()

    current_net = ""
    net_count = 0
    node_count = 0
    no_connect_node_count = 0
    for index, line in enumerate(pstxnet_lines):
        if line.startswith("NET_NAME"):
            net_count += 1
            quoted = (
                _PSTXNET_QUOTED_RE.match(pstxnet_lines[index + 1])
                if index + 1 < len(pstxnet_lines)
                else None
            )
            current_net = quoted.group(1) if quoted else ""
            continue
        if _PSTXNET_NODE_RE.match(line):
            node_count += 1
            if current_net == "NC":
                no_connect_node_count += 1

    refs: list[str] = []
    for index, line in enumerate(pstxprt_lines):
        if not line.startswith("PART_NAME") or index + 1 >= len(pstxprt_lines):
            continue
        if match := _PSTXPRT_PART_RE.match(pstxprt_lines[index + 1]):
            refs.append(match.group(1))

    primitive_count = sum(1 for line in pstchip_lines if _PSTCHIP_PRIMITIVE_RE.match(line))
    primitive_pin_count = sum(1 for line in pstchip_lines if _PSTCHIP_PIN_NUMBER_RE.match(line))

    return PackagedNetlistSummary(
        root=root,
        net_count=net_count,
        node_count=node_count,
        no_connect_node_count=no_connect_node_count,
        part_count=len(refs),
        unique_refdes_count=len(set(refs)),
        primitive_count=primitive_count,
        primitive_pin_count=primitive_pin_count,
    )


def parse_placement_log(path: Path) -> PlacementLog:
    board_file = ""
    output_file = ""
    placed_component_count = 0
    for line in path.read_text(errors="replace").splitlines():
        if match := _PLACEMENT_BOARD_RE.match(line):
            board_file = match.group(1)
            continue
        if match := _PLACEMENT_OUTPUT_RE.match(line):
            output_file = match.group(1)
            continue
        if match := _PLACEMENT_COUNT_RE.match(line):
            placed_component_count = int(match.group(1))
    return PlacementLog(
        path=path,
        board_file=board_file,
        output_file=output_file,
        placed_component_count=placed_component_count,
    )


def run_kicad_allegro_conversion_report(
    source_board: Path, output_board: Path
) -> KicadConversionReport:
    executable = shutil.which("kicad-cli")
    if executable is None:
        msg = "kicad-cli executable was not found on PATH"
        raise FileNotFoundError(msg)
    resolved_source = source_board.resolve(strict=True)
    resolved_output = output_board.resolve(strict=False)
    completed = subprocess.run(
        [executable, "pcb", "convert", str(resolved_source), "--output", str(resolved_output)],
        check=True,
        capture_output=True,
        text=True,
        timeout=KICAD_CONVERSION_TIMEOUT_SECONDS,
    )
    text = resolved_output.read_text(errors="replace")
    return KicadConversionReport(
        source_board=resolved_source,
        output_board=resolved_output,
        output_size_bytes=resolved_output.stat().st_size,
        layer_count=sum(1 for line in text.splitlines() if _KICAD_LAYER_RE.match(line)),
        stdout=completed.stdout,
        stderr=completed.stderr,
    )
